### ISSUE TITLE
Remove DRAFT from title

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-website-personas#7]
Currently the title is "WAI Redesign Personas [DRAFT]".  This needs to be updated to "WAI Redesign Personas".  It's probably also prudent to add an intro sentence that says "Approved by EOWG 15 July 2016."  I'd do it except I can't figure out how.  I'm guessing only Eric has the authority to do this -- as the person who set the page up.  Thanks.

**Comment by yatil** [comment]
You can change the Draft from the title in the [config file](https://github.com/w3c/wai-website-personas/blob/gh-pages/_config.yml), and add a sentence in the [index.html](https://github.com/w3c/wai-website-personas/blob/gh-pages/index.html) file – you should have edit rights and you don’t need to do a pull request but commit directly to the gh-pages branch.

**Comment by happywebdiva** [comment]
Fixed
